ALTER TABLE "Patient" ADD COLUMN IF NOT EXISTS "allowsMessages" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Patient" ADD COLUMN IF NOT EXISTS "lastBirthdayMessageAt" TIMESTAMP(3);
ALTER TABLE "Patient" ADD COLUMN IF NOT EXISTS "birthdayMessageYear" INTEGER;
