ALTER TYPE "NotificationEventType" ADD VALUE IF NOT EXISTS 'BIRTHDAY_MESSAGE_SENT';
ALTER TYPE "NotificationEventType" ADD VALUE IF NOT EXISTS 'BIRTHDAY_MESSAGE_FAILED';
ALTER TYPE "NotificationEventType" ADD VALUE IF NOT EXISTS 'BIRTHDAY_MESSAGE_JOB_COMPLETED';
